routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');


Route::resource('cities', App\Http\Controllers\cityController::class);


Route::resource('locations', App\Http\Controllers\locationController::class);


Route::resource('metrics', App\Http\Controllers\metricController::class);


Route::resource('recordHistories', App\Http\Controllers\record_historyController::class);


Route::resource('records', App\Http\Controllers\recordController::class);

app/Models/Coreui/city.php
<?php

namespace App\Models\Coreui;

use Eloquent as Model;



/**
 * Class city
 * @package App\Models\Coreui
 * @version January 27, 2021, 9:28 am UTC
 *
 * @property string $nameid
 * @property string $iso
 * @property string $display_name
 * @property integer $estatus
 */
class city extends Model
{


    public $table = 'city';
    



    public $fillable = [
        'nameid',
        'iso',
        'display_name',
        'estatus'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nameid' => 'string',
        'iso' => 'string',
        'display_name' => 'string',
        'estatus' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Models/Coreui/location.php
<?php

namespace App\Models\Coreui;

use Eloquent as Model;



/**
 * Class location
 * @package App\Models\Coreui
 * @version January 27, 2021, 9:35 am UTC
 *
 * @property number $latitude
 * @property number $longitude
 * @property number $area
 * @property string $mapcode
 * @property string $city_nameid
 */
class location extends Model
{


    public $table = 'location';
    



    public $fillable = [
        'latitude',
        'longitude',
        'area',
        'mapcode',
        'city_nameid'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'location_id' => 'integer',
        'latitude' => 'double',
        'longitude' => 'double',
        'area' => 'double',
        'mapcode' => 'string',
        'city_nameid' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Models/Coreui/metric.php
<?php

namespace App\Models\Coreui;

use Eloquent as Model;



/**
 * Class metric
 * @package App\Models\Coreui
 * @version January 27, 2021, 9:39 am UTC
 *
 * @property string $nameid
 * @property string $iso
 * @property string $display_name
 * @property integer $estatus
 */
class metric extends Model
{


    public $table = 'metric';
    



    public $fillable = [
        'nameid',
        'iso',
        'display_name',
        'estatus'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'nameid' => 'string',
        'iso' => 'string',
        'display_name' => 'string',
        'estatus' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/API/Coreui/cityAPIController.php
<?php

namespace App\Http\Controllers\API\Coreui;

use App\Http\Requests\API\Coreui\CreatecityAPIRequest;
use App\Http\Requests\API\Coreui\UpdatecityAPIRequest;
use App\Models\Coreui\city;
use App\Repositories\Coreui\cityRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Http\Resources\Coreui\cityResource;
use Response;

/**
 * Class cityController
 * @package App\Http\Controllers\API\Coreui
 */

class cityAPIController extends AppBaseController
{
    /** @var  cityRepository */
    private $cityRepository;

    public function __construct(cityRepository $cityRepo)
    {
        $this->cityRepository = $cityRepo;
    }

    /**
     * Display a listing of the city.
     * GET|HEAD /cities
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $cities = $this->cityRepository->all(
            $request->except(['skip', 'limit']),
            $request->get('skip'),
            $request->get('limit')
        );

        return $this->sendResponse(cityResource::collection($cities), 'Cities retrieved successfully');
    }

    /**
     * Store a newly created city in storage.
     * POST /cities
     *
     * @param CreatecityAPIRequest $request
     *
     * @return Response
     */
    public function store(CreatecityAPIRequest $request)
    {
        $input = $request->all();

        $city = $this->cityRepository->create($input);

        return $this->sendResponse(new cityResource($city), 'City saved successfully');
    }

    /**
     * Display the specified city.
     * GET|HEAD /cities/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var city $city */
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            return $this->sendError('City not found');
        }

        return $this->sendResponse(new cityResource($city), 'City retrieved successfully');
    }

    /**
     * Update the specified city in storage.
     * PUT/PATCH /cities/{id}
     *
     * @param int $id
     * @param UpdatecityAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatecityAPIRequest $request)
    {
        $input = $request->all();

        /** @var city $city */
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            return $this->sendError('City not found');
        }

        $city = $this->cityRepository->update($input, $id);

        return $this->sendResponse(new cityResource($city), 'city updated successfully');
    }

    /**
     * Remove the specified city from storage.
     * DELETE /cities/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var city $city */
        $city = $this->cityRepository->find($id);

        if (empty($city)) {
            return $this->sendError('City not found');
        }

        $city->delete();

        return $this->sendSuccess('City deleted successfully');
    }
}

app/Http/Controllers/API/Coreui/locationAPIController.php
<?php

namespace App\Http\Controllers\API\Coreui;

use App\Http\Requests\API\Coreui\CreatelocationAPIRequest;
use App\Http\Requests\API\Coreui\UpdatelocationAPIRequest;
use App\Models\Coreui\location;
use App\Repositories\Coreui\locationRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Http\Resources\Coreui\locationResource;
use Response;

/**
 * Class locationController
 * @package App\Http\Controllers\API\Coreui
 */

class locationAPIController extends AppBaseController
{
    /** @var  locationRepository */
    private $locationRepository;

    public function __construct(locationRepository $locationRepo)
    {
        $this->locationRepository = $locationRepo;
    }

    /**
     * Display a listing of the location.
     * GET|HEAD /locations
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $locations = $this->locationRepository->all(
            $request->except(['skip', 'limit']),
            $request->get('skip'),
            $request->get('limit')
        );

        return $this->sendResponse(locationResource::collection($locations), 'Locations retrieved successfully');
    }

    /**
     * Store a newly created location in storage.
     * POST /locations
     *
     * @param CreatelocationAPIRequest $request
     *
     * @return Response
     */
    public function store(CreatelocationAPIRequest $request)
    {
        $input = $request->all();

        $location = $this->locationRepository->create($input);

        return $this->sendResponse(new locationResource($location), 'Location saved successfully');
    }

    /**
     * Display the specified location.
     * GET|HEAD /locations/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var location $location */
        $location = $this->locationRepository->find($id);

        if (empty($location)) {
            return $this->sendError('Location not found');
        }

        return $this->sendResponse(new locationResource($location), 'Location retrieved successfully');
    }

    /**
     * Update the specified location in storage.
     * PUT/PATCH /locations/{id}
     *
     * @param int $id
     * @param UpdatelocationAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatelocationAPIRequest $request)
    {
        $input = $request->all();

        /** @var location $location */
        $location = $this->locationRepository->find($id);

        if (empty($location)) {
            return $this->sendError('Location not found');
        }

        $location = $this->locationRepository->update($input, $id);

        return $this->sendResponse(new locationResource($location), 'location updated successfully');
    }

    /**
     * Remove the specified location from storage.
     * DELETE /locations/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var location $location */
        $location = $this->locationRepository->find($id);

        if (empty($location)) {
            return $this->sendError('Location not found');
        }

        $location->delete();

        return $this->sendSuccess('Location deleted successfully');
    }
}

app/Http/Controllers/API/Coreui/metricAPIController.php
<?php

namespace App\Http\Controllers\API\Coreui;

use App\Http\Requests\API\Coreui\CreatemetricAPIRequest;
use App\Http\Requests\API\Coreui\UpdatemetricAPIRequest;
use App\Models\Coreui\metric;
use App\Repositories\Coreui\metricRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Http\Resources\Coreui\metricResource;
use Response;

/**
 * Class metricController
 * @package App\Http\Controllers\API\Coreui
 */

class metricAPIController extends AppBaseController
{
    /** @var  metricRepository */
    private $metricRepository;

    public function __construct(metricRepository $metricRepo)
    {
        $this->metricRepository = $metricRepo;
    }

    /**
     * Display a listing of the metric.
     * GET|HEAD /metrics
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $metrics = $this->metricRepository->all(
            $request->except(['skip', 'limit']),
            $request->get('skip'),
            $request->get('limit')
        );

        return $this->sendResponse(metricResource::collection($metrics), 'Metrics retrieved successfully');
    }

    /**
     * Store a newly created metric in storage.
     * POST /metrics
     *
     * @param CreatemetricAPIRequest $request
     *
     * @return Response
     */
    public function store(CreatemetricAPIRequest $request)
    {
        $input = $request->all();

        $metric = $this->metricRepository->create($input);

        return $this->sendResponse(new metricResource($metric), 'Metric saved successfully');
    }

    /**
     * Display the specified metric.
     * GET|HEAD /metrics/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var metric $metric */
        $metric = $this->metricRepository->find($id);

        if (empty($metric)) {
            return $this->sendError('Metric not found');
        }

        return $this->sendResponse(new metricResource($metric), 'Metric retrieved successfully');
    }

    /**
     * Update the specified metric in storage.
     * PUT/PATCH /metrics/{id}
     *
     * @param int $id
     * @param UpdatemetricAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatemetricAPIRequest $request)
    {
        $input = $request->all();

        /** @var metric $metric */
        $metric = $this->metricRepository->find($id);

        if (empty($metric)) {
            return $this->sendError('Metric not found');
        }

        $metric = $this->metricRepository->update($input, $id);

        return $this->sendResponse(new metricResource($metric), 'metric updated successfully');
    }

    /**
     * Remove the specified metric from storage.
     * DELETE /metrics/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var metric $metric */
        $metric = $this->metricRepository->find($id);

        if (empty($metric)) {
            return $this->sendError('Metric not found');
        }

        $metric->delete();

        return $this->sendSuccess('Metric deleted successfully');
    }
}

app/Http/Controllers/API/Coreui/recordAPIController.php
<?php

namespace App\Http\Controllers\API\Coreui;

use App\Http\Requests\API\Coreui\CreaterecordAPIRequest;
use App\Http\Requests\API\Coreui\UpdaterecordAPIRequest;
use App\Models\Coreui\record;
use App\Repositories\Coreui\recordRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\AppBaseController;
use App\Http\Resources\Coreui\recordResource;
use Response;

/**
 * Class recordController
 * @package App\Http\Controllers\API\Coreui
 */

class recordAPIController extends AppBaseController
{
    /** @var  recordRepository */
    private $recordRepository;

    public function __construct(recordRepository $recordRepo)
    {
        $this->recordRepository = $recordRepo;
    }

    /**
     * Display a listing of the record.
     * GET|HEAD /records
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $records = $this->recordRepository->all(
            $request->except(['skip', 'limit']),
            $request->get('skip'),
            $request->get('limit')
        );

        return $this->sendResponse(recordResource::collection($records), 'Records retrieved successfully');
    }

    /**
     * Store a newly created record in storage.
     * POST /records
     *
     * @param CreaterecordAPIRequest $request
     *
     * @return Response
     */
    public function store(CreaterecordAPIRequest $request)
    {
        $input = $request->all();

        $record = $this->recordRepository->create($input);

        return $this->sendResponse(new recordResource($record), 'Record saved successfully');
    }

    /**
     * Display the specified record.
     * GET|HEAD /records/{id}
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        /** @var record $record */
        $record = $this->recordRepository->find($id);

        if (empty($record)) {
            return $this->sendError('Record not found');
        }

        return $this->sendResponse(new recordResource($record), 'Record retrieved successfully');
    }

    /**
     * Update the specified record in storage.
     * PUT/PATCH /records/{id}
     *
     * @param int $id
     * @param UpdaterecordAPIRequest $request
     *
     * @return Response
     */
    public function update($id, UpdaterecordAPIRequest $request)
    {
        $input = $request->all();

        /** @var record $record */
        $record = $this->recordRepository->find($id);

        if (empty($record)) {
            return $this->sendError('Record not found');
        }

        $record = $this->recordRepository->update($input, $id);

        return $this->sendResponse(new recordResource($record), 'record updated successfully');
    }

    /**
     * Remove the specified record from storage.
     * DELETE /records/{id}
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        /** @var record $record */
        $record = $this->recordRepository->find($id);

        if (empty($record)) {
            return $this->sendError('Record not found');
        }

        $record->delete();

        return $this->sendSuccess('Record deleted successfully');
    }
}

resources/views/coreui/records/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('coreui.records.index') !!}">Record</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Record</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'coreui.records.store']) !!}

                                   @include('coreui.records.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/coreui/records/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('coreui.records.index') !!}">Record</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Record</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($record, ['route' => ['coreui.records.update', $record->id], 'method' => 'patch']) !!}

                              @include('coreui.records.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/coreui/records/fields.blade.php
<!-- Date Field -->
<div class="form-group col-sm-6">
    {!! Form::label('date', 'Date:') !!}
    {!! Form::text('date', null, ['class' => 'form-control','id'=>'date']) !!}
</div>

@push('scripts')
   <script type="text/javascript">
           $('#date').datetimepicker({
               format: 'YYYY-MM-DD HH:mm:ss',
               useCurrent: true,
               icons: {
                   up: "icon-arrow-up-circle icons font-2xl",
                   down: "icon-arrow-down-circle icons font-2xl"
               },
               sideBySide: true
           })
       </script>
@endpush


<!-- City Nameid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('city_nameid', 'City Nameid:') !!}
    {!! Form::text('city_nameid', null, ['class' => 'form-control']) !!}
</div>

<!-- Value Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::number('value', null, ['class' => 'form-control']) !!}
</div>

<!-- Metric Nameid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('metric_nameid', 'Metric Nameid:') !!}
    {!! Form::text('metric_nameid', null, ['class' => 'form-control']) !!}
</div>

<!-- History Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('history_id', 'History Id:') !!}
    {!! Form::number('history_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('coreui.records.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/coreui/records/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Records</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             records
                             <a class="pull-right" href="{{ route('coreui.records.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('coreui.records.table')
                              <div class="pull-right mr-3">
                                     
        @include('coreui-templates::common.paginate', ['records' => $records])

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/coreui/records/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('coreui.records.index') }}">Record</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('coreui.records.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('coreui.records.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/coreui/records/show_fields.blade.php
<!-- Record Id Field -->
<div class="form-group">
    {!! Form::label('record_id', 'Record Id:') !!}
    <p>{{ $record->record_id }}</p>
</div>

<!-- Date Field -->
<div class="form-group">
    {!! Form::label('date', 'Date:') !!}
    <p>{{ $record->date }}</p>
</div>

<!-- City Nameid Field -->
<div class="form-group">
    {!! Form::label('city_nameid', 'City Nameid:') !!}
    <p>{{ $record->city_nameid }}</p>
</div>

<!-- Value Field -->
<div class="form-group">
    {!! Form::label('value', 'Value:') !!}
    <p>{{ $record->value }}</p>
</div>

<!-- Metric Nameid Field -->
<div class="form-group">
    {!! Form::label('metric_nameid', 'Metric Nameid:') !!}
    <p>{{ $record->metric_nameid }}</p>
</div>

<!-- History Id Field -->
<div class="form-group">
    {!! Form::label('history_id', 'History Id:') !!}
    <p>{{ $record->history_id }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $record->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $record->updated_at }}</p>
</div>

resources/views/coreui/records/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="records-table">
        <thead>
            <tr>
                <th>Record Id</th>
        <th>City Nameid</th>
        <th>Metric Nameid</th>
        <th>History Id</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($records as $record)
            <tr>
                <td>{{ $record->record_id }}</td>
            <td>{{ $record->city_nameid }}</td>
            <td>{{ $record->metric_nameid }}</td>
            <td>{{ $record->history_id }}</td>
                <td>
                    {!! Form::open(['route' => ['coreui.records.destroy', $record->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('coreui.records.show', [$record->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('coreui.records.edit', [$record->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>